import { Deck } from './schema';

export const SAMPLE_DECKS: Deck[] = [
  {
    id: 'deck-001',
    title: 'Q4 Business Review',
    prompt: 'Create a comprehensive Q4 business review presentation for the executive team',
    audience: 'Executive Team',
    tone: 'professional',
    contentType: 'business',
    slideCount: 8,
    themeId: 'cobalt',
    status: 'ready',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    deckJson: {
      themeId: 'cobalt',
      slides: [
        {
          id: 's1',
          type: 'hero-title',
          layout: 'title-hero-left',
          purpose: 'intro',
          title: 'Q4 Business Review',
          subtitle: 'Performance Analysis & Strategic Outlook',
          body: 'FY 2024 | Executive Presentation',
          imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
          notes: 'Opening slide — set the stage for the quarterly review',
        },
        {
          id: 's2',
          type: 'agenda',
          layout: 'agenda-clean',
          purpose: 'agenda',
          title: 'Today\'s Agenda',
          bullets: [
            '01 — Revenue Performance & KPIs',
            '02 — Product Milestones',
            '03 — Market Expansion',
            '04 — Team Growth',
            '05 — Q1 Roadmap',
          ],
          notes: 'Walk through the agenda briefly',
        },
        {
          id: 's3',
          type: 'kpi-dashboard',
          layout: 'stat-cards-grid',
          purpose: 'data',
          title: 'Key Performance Indicators',
          subtitle: 'Q4 2024 at a Glance',
          kpis: [
            { value: '$4.2M', label: 'Total Revenue', trend: '+24%' },
            { value: '1,847', label: 'Active Customers', trend: '+18%' },
            { value: '94.3%', label: 'Customer Satisfaction', trend: '+2.1%' },
            { value: '3.2x', label: 'ARR Growth', trend: '+0.8x' },
          ],
          notes: 'Highlight the ARR growth metric — board will focus on this',
        },
        {
          id: 's4',
          type: 'two-column',
          layout: 'two-column-explainer',
          purpose: 'content',
          title: 'Product Milestones',
          subtitle: 'Q4 Shipped Features',
          bullets: [
            'AI-powered recommendations engine',
            'Real-time collaboration suite',
            'Enterprise SSO integration',
            'Mobile app v3.0 launch',
            'API v2 with 99.9% uptime SLA',
          ],
          notes: 'Feature highlights for the quarter',
        },
        {
          id: 's5',
          type: 'process-flow',
          layout: 'horizontal-process',
          purpose: 'process',
          title: 'Q1 2025 Strategic Roadmap',
          processSteps: [
            { number: 1, title: 'Platform Scale', description: 'Infrastructure & performance improvements' },
            { number: 2, title: 'Market Expansion', description: 'European & APAC market entry' },
            { number: 3, title: 'Enterprise Push', description: 'Fortune 500 sales motion' },
            { number: 4, title: 'AI Suite', description: 'Next-gen intelligence features' },
          ],
          notes: 'Focus on the enterprise push — biggest opportunity',
        },
        {
          id: 's6',
          type: 'quote',
          layout: 'quote-impact',
          purpose: 'quote',
          title: 'Customer Voice',
          quote: 'This platform transformed how our team collaborates. We\'ve seen a 40% reduction in time-to-delivery and the ROI has been phenomenal.',
          quoteAuthor: 'Sarah Chen, VP Engineering @ TechCorp',
          notes: 'Strong social proof to close the deck',
        },
        {
          id: 's7',
          type: 'closing',
          layout: 'closing-contact',
          purpose: 'closing',
          title: 'Let\'s Build the Future Together',
          subtitle: 'Thank you for your continued trust and partnership.',
          body: 'Q1 planning sessions begin January 8th',
          notes: 'End on a high note — be inspiring',
        },
      ],
    },
  },
  {
    id: 'deck-002',
    title: 'Product Launch: Aurora AI',
    prompt: 'Product launch presentation for Aurora AI, our new AI-powered analytics platform',
    audience: 'Potential Customers & Press',
    tone: 'inspiring',
    contentType: 'product',
    slideCount: 7,
    themeId: 'aurora',
    status: 'ready',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    deckJson: {
      themeId: 'aurora',
      slides: [
        {
          id: 'p1',
          type: 'hero-title',
          layout: 'title-hero-right',
          purpose: 'intro',
          title: 'Introducing Aurora AI',
          subtitle: 'Analytics that think ahead',
          imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
          notes: 'Dramatic hero slide — big moment',
        },
        {
          id: 'p2',
          type: 'section-divider',
          layout: 'dark-accent',
          purpose: 'section-header',
          title: 'The Problem',
          subtitle: 'Data everywhere. Insights nowhere.',
          notes: 'Set up the problem clearly',
        },
        {
          id: 'p3',
          type: 'comparison',
          layout: 'comparison-split',
          purpose: 'comparison',
          title: 'Before vs. After Aurora',
          comparisonColumns: [
            {
              title: 'Without Aurora',
              items: ['Manual data aggregation', '3-5 day insight lag', 'Siloed dashboards', 'Generic reports', 'Reactive decisions'],
              highlight: false,
            },
            {
              title: 'With Aurora AI',
              items: ['Automated intelligence', 'Real-time insights', 'Unified data fabric', 'Predictive analytics', 'Proactive strategy'],
              highlight: true,
            },
          ],
          notes: 'This slide wins deals — make it land',
        },
        {
          id: 'p4',
          type: 'kpi-dashboard',
          layout: 'stat-cards-grid',
          purpose: 'data',
          title: 'Aurora by the Numbers',
          kpis: [
            { value: '10x', label: 'Faster Insights', trend: 'vs manual' },
            { value: '89%', label: 'Prediction Accuracy', trend: 'avg customer' },
            { value: '6hrs', label: 'Saved Per Week', trend: 'per analyst' },
            { value: '340+', label: 'Beta Customers', trend: 'loving it' },
          ],
          notes: 'Numbers speak for themselves',
        },
        {
          id: 'p5',
          type: 'closing',
          layout: 'closing-contact',
          purpose: 'closing',
          title: 'Start Your Free Trial',
          subtitle: 'Join 340+ companies already seeing the future of analytics.',
          body: 'aurora.ai/start — No credit card required',
          notes: 'Strong CTA to close',
        },
      ],
    },
  },
  {
    id: 'deck-003',
    title: 'Series A Investor Pitch',
    prompt: 'Series A fundraising pitch deck for investors',
    audience: 'Venture Capital Investors',
    tone: 'persuasive',
    contentType: 'business',
    slideCount: 10,
    themeId: 'sand',
    status: 'draft',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    deckJson: {
      themeId: 'sand',
      slides: [
        {
          id: 'i1',
          type: 'hero-title',
          layout: 'title-hero-left',
          purpose: 'intro',
          title: 'Redefining How Teams Work',
          subtitle: 'Series A | $8M Round',
          imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
          notes: 'Confident, bold opening',
        },
        {
          id: 'i2',
          type: 'timeline',
          layout: 'milestone-timeline',
          purpose: 'timeline',
          title: 'Our Journey',
          timelineMilestones: [
            { date: 'Jan 2022', title: 'Founded', description: 'Team of 3 with a vision' },
            { date: 'Jun 2022', title: 'First $1M ARR', description: 'Pre-seed raised, product-market fit' },
            { date: 'Jan 2023', title: 'Seed Round', description: '$2M raised, 50+ customers' },
            { date: 'Dec 2023', title: '$4M ARR', description: '200+ enterprise customers' },
            { date: 'Now', title: 'Series A', description: 'Ready to scale globally' },
          ],
          notes: 'Show momentum and execution speed',
        },
        {
          id: 'i3',
          type: 'closing',
          layout: 'closing-contact',
          purpose: 'closing',
          title: 'Join Us on This Journey',
          subtitle: 'Let\'s build the category-defining platform together.',
          body: 'founders@company.com | deck.company.com',
          notes: 'Inspire confidence, invite follow-up',
        },
      ],
    },
  },
];
